name = "airtable-form-handler"
type = "javascript"

account_id = "9e4a4e7ba6545748280534a6833116d4"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-16"

[vars]
AIRTABLE_BASE_ID = "appLbpNFYw6YvWIVn"
AIRTABLE_TABLE_NAME = "Form Submissions"
